version: '3.8'

services:
  medical-book-service:
    build: .
    ports:
      - "8000:8000"
    environment:
      - BASIC_AUTH_USERNAME=admin
      - BASIC_AUTH_PASSWORD=secure_password_here
      - EXTERNAL_API_URL=https://elmk.rospotrebnadzor.ru/registry
      - EXTERNAL_API_TIMEOUT=30
      - RATE_LIMIT_REQUESTS=100
      - RATE_LIMIT_WINDOW=3600
      - LOG_LEVEL=INFO
      - LOG_FORMAT=json
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=false
      - SECRET_KEY=your-secret-key-here-change-in-production
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s